import streamlit as st
import joblib
import Predictions
import numpy as np

model = joblib.load("model.pkl")

st.header("Bengaluru House Price Predictions")

area_type = st.selectbox("Area Type: ", options=['Super built-up  Area', 'Built-up  Area', 'Plot  Area', 'Carpet  Area'])

balcony = st.slider("Balcony", 0, 5)

location = st.selectbox("Location", options=['Electronic City Phase II', 'Chikka Tirupathi',
       'Lingadheeranahalli', 'Whitefield', '7th Phase JP Nagar',
       'Sarjapur', 'Mysore Road', 'Bisuvanahalli',
       'Raja Rajeshwari Nagar', 'Ramakrishnappa Layout', 'Binny Pete',
       'Thanisandra', ' Thanisandra', 'Electronic City',
       'Ramagondanahalli', 'Yelahanka', 'Hebbal', 'Kanakpura Road',
       'Kundalahalli', 'Sarjapur  Road', 'Ganga Nagar', 'Doddathoguru',
       'Adarsh Nagar', 'Bhoganhalli', 'Lakshminarayana Pura',
       'Begur Road', 'Varthur', 'Gunjur', 'Hegde Nagar', 'Haralur Road',
       'Hennur Road', 'Cholanayakanahalli', 'Kodanda Reddy Layout',
       'EPIP Zone', 'Dasanapura', 'Kasavanhalli', 'Sanjay nagar',
       'Kengeri', 'Yeshwanthpur', 'Chandapura', 'Kothanur',
       'Green View Layout', 'Shantiniketan Layout', 'Rajaji Nagar',
       'Devanahalli', 'Byatarayanapura', 'Akshaya Nagar',
       'LB Shastri Nagar', 'Hormavu', 'Peenya', 'Kudlu Gate',
       '8th Phase JP Nagar', 'Chandra Layout', 'Anandapura',
       'Kengeri Satellite Town', 'Basavanapura', 'Kannamangala',
       'Hulimavu', 'Hosa Road', 'Keshava Nagar', 'RMV Extension',
       'Tejaswini Nagar', 'Jai Bheema Nagar', 'Attibele',
       'CV Raman Nagar', 'Malleshwaram', 'Hebbal Kempapura',
       'Vijayanagar', 'KR Puram', 'Marathahalli', 'Pattandur Agrahara',
       'HSR Layout', 'Kadugodi', 'Kogilu', 'Panathur', 'Kammasandra',
       'Electronics City Phase 1', 'Tala Cauvery Layout', 'Dasarahalli',
       'Koramangala', 'Muthurayya Swamy Layout', 'Budigere',
       'Dodda Nekkundi Extension', 'Mylasandra', 'Kalyan nagar',
       'Ashwath Nagar', 'Ncpr Industrial Layout', 'Meenakunte',
       'OMBR Layout', 'Coffee Board Layout', 'Ambedkar Nagar',
       'Geleyara Balaga Layout', 'Kalena Agrahara', 'Talaghattapura',
       'Balagere', 'Jigani', 'Gollarapalya Hosahalli', 'Old Madras Road',
       'Silver Springs Layout', '9th Phase JP Nagar', 'Jakkur',
       'Maruthi Sevanagar', 'RMV 2nd Stage', 'Singasandra', 'AECS Layout',
       'Mallasandra', 'Begur', 'JP Nagar', 'Sunder Ram Shetty Nagar',
       'Motappa Layout', 'Kaval Byrasandra', 'Kaggalipura',
       'Basavanna Nagar', '6th Phase JP Nagar', 'Ulsoor', 'Uttarahalli',
       'Thigalarapalya', ' Devarachikkanahalli', 'Bommasandra',
       'Prashanth Nagar', 'Suragajakkanahalli', 'Ardendale', 'Harlur',
       'Sampigehalli', 'Kodihalli', 'Magadi Road', 'Narayanapura',
       'Hennur', '5th Phase JP Nagar', 'Kodigehaali', 'Bannerghatta Road',
       'Gopalapura', 'Billekahalli', 'Jalahalli', 'Sompura',
       'Ashirvad Colony', 'Dodda Nekkundi', 'Hosur Road', 'Amco Colony',
       'Ambalipura', 'Hoodi', 'Samethanahalli', 'Brookefield',
       'Suddaguntepalya', 'Udayapur Village', 'Bellandur', 'Vittasandra',
       'Giri Nagar', 'Chikkabidarakallu', '1 Giri Nagar', 'Hoysalanagar',
       'Defence Colony', 'Amruthahalli', 'Patelappa Layout',
       'Subramanyapura', '3rd Block Hrbr Layout', 'Surabhi Layout',
       'Omkar Nagar', 'Kambipura', 'VHBCS Layout', 'Rajiv Nagar',
       'Gattahalli', 'Arekere', 'Mico Layout', 'Munnekollal',
       'Banashankari Stage III', 'Dooravani Nagar', 'JCR Layout',
       'Nehru Nagar', 'Sneha Colony', 'Konanakunte', 'Ashwini layout',
       'Gottigere', 'HRBR Layout', 'Kanakapura', 'Tumkur Road',
       'Hosahalli', 'Jalahalli West', 'GM Palaya', 'Jalahalli East',
       'Hosakerehalli', 'Nagondanahalli', 'Shanthala Nagar',
       'Bettahalsoor', 'Ambedkar Colony', 'Avalahalli', 'Prakruthi Nagar',
       'Abbigere', 'Tindlu', 'Green Garden Layout', 'Gubbalala',
       'Dairy Circle', 'Narayana Nagar 1st Block', 'KSRTC Layout',
       'New Gurappana Palya', 'Vadarpalya', 'Kudlu', 'Old Airport Road',
       'Vishwapriya Layout', 'Banashankari Stage VI', 'Battarahalli',
       'HMT Layout', 'Kaggadasapura', 'ITI Layout', 'Yelahanka New Town',
       'Sahakara Nagar', 'Rachenahalli', 'Kodbisanhalli',
       'Kodichikkanahalli', 'Bendiganahalli', 'Ferrar Nagar',
       'Green Glen Layout', 'M.G Road', 'Horamavu Banaswadi',
       '1st Phase JP Nagar', 'Kaverappa Layout', 'Devarabisanahalli',
       'Somasundara Palya', 'Vidyaranyapura', 'Babusapalaya',
       'Nagappa Reddy Layout', 'TC Palaya', 'Suraksha Nagar',
       'Iblur Village', 'Yelachenahalli', 'Basava Nagar',
       '2nd Block Hrbr Layout', 'Basapura', 'Channasandra',
       'Singena Agrahara', 'Mango Garden Layout', 'Choodasandra',
       'Indira Nagar', 'Sai Gardens', 'Mahadevpura', 'Hanumanth Nagar',
       'Basaveshwara Nagar', 'Kaikondrahalli', 'RWF West Colony',
       'Bileshivale', 'Neeladri Nagar', 'Frazer Town', 'Jaya Nagar East',
       'Iggalur', 'Banashankari', 'Chamrajpet', 'VGP Layout',
       'Vasanth nagar', 'Kalkere', 'Maragondanahalli', 'Ramamurthy Nagar',
       'Garudachar Palya', 'Roopena Agrahara', 'Gollahalli',
       'Sonnenahalli', 'Nagarbhavi', 'Bommanahalli', 'Chikkalasandra',
       'Dommasandra', 'Byadarahalli', 'Judicial Layout',
       'Outer Ring Road East', 'Vinayaka Nagar', 'GB Palya',
       'Ashwathnagar', 'Kasturi Nagar', 'Belathur', 'Srirampura',
       'Devanahalli Road', 'Ejipura', 'Green Woods Layout',
       'Craig Park Layout', 'Immadihalli', 'Muneshwara Nagar',
       'Rayasandra', 'Malleshpalya', 'Parappana Agrahara',
       'Lakshmi Layout', 'Thirumenahalli', 'KPC Layout',
       'Daadys Gaarden Layout', 'Kothannur', 'Marsur', 'Karuna Nagar',
       'Kallumantapa', 'Malimakanapura', 'Medahalli',
       'Rustam Bagh Layout', 'Garden Layout', 'T K Reddy Layout',
       'Doddanekundi', 'Venkatadri Layout', 'Bommenahalli',
       'Mahaganapathy Nagar', 'HBR Layout', 'Vittal Nagar',
       'Bhuvaneshwari Nagar', 'Prithvi Layout', 'Domlur', 'Thubarahalli',
       'Jaya Mahal layout', 'BSM Extension', 'Vijinapura', 'Byrasandra',
       'Chowdeshwari Layout', 'Sector 2 HSR Layout', 'Padmanabhanagar',
       'Badavala Nagar', '4th Block Koramangala', 'Belatur',
       'Nallurhalli', 'Kereguddadahalli', 'Laxmi Sagar Layout',
       'Bannerghatta', 'Harappanahalli', 'BTM Layout', 'Kanaka Nagar',
       'NR Colony', 'Byagadadhenahalli', 'Doddabommasandra',
       'Sarjapura - Attibele Road', 'Maruthi Layout',
       'Sree Narayana Nagar', 'Tunganagara', 'Nagavara',
       'Remco Bhel Layout', 'Chokkasandra', 'Panduranga Nagar',
       'Jakkur Plantation', '1st Block Koramangala',
       'Shree Ananth Nagar Layout', 'Hoskote', 'Sector 1 HSR Layout',
       'BTM 2nd Stage', 'Ananth Nagar', 'Sundar Ram Shetty Nagar',
       'Alfa Garden Layout', 'Hoodi Layout', 'Seegehalli',
       'Gaundanapalya', '2nd Phase JP Nagar', 'Doctors Layout',
       'Basavangudi', 'Vishwapriya Nagar', 'Sarakki Nagar', 'R.T. Nagar',
       'Sector 7 HSR Layout', 'Hennur Gardens',
       'Howthinarayanappa Garden', 'Bharathi Nagar', 'Cambridge Layout',
       'Doddakannelli', 'Cox Town', 'Pulkeshi Nagar', 'Jayanagar',
       ' Bhoganhalli', 'Pai Layout', '8th block Koramangala', 'Bidadi',
       'Amruthnagar', 'Rajiv Gandhi Nagar', 'Anekal',
       'Bhagyalakshmi Avenue', 'Doddaballapur', 'Horamavu Agara',
       'Chinnapanahalli', 'Balaji Gardens Layout', ' Rachenahalli',
       'Akshaya Vana', 'Channasandra Layout', 'Gopalkrishna Nagar',
       'Volagerekallahalli', 'Keerthi Layout', 'Shikaripalya', 'Hagadur',
       'Soundarya Layout', 'Dollars Layout', 'Nagavarapalya',
       'Sultan Palaya', 'Gopal Reddy Layout', 'Thurahalli',
       'Murugeshpalya', 'Kadubeesanahalli', 'Cleveland Town',
       'Kada Agrahara', 'Bellari Road', 'Abbaiah Reddy Layout',
       'Tata Nagar', ' Devarabeesana Halli', 'Brindavan Nagar',
       'Seetharampalya', 'B Narayanapura', 'Raghuvanahalli',
       'Wilson Garden', 'Challaghatta', 'KR Garden', 'Kathriguppe',
       'Sahyadri Layout', 'Bagalur', 'P Krishnappa Layout',
       'Crimson Layout', 'Kyalasanahalli', 'Ckikkakammana Halli',
       'Munivenkatppa Layout', 'Vijaya Bank Layout', 'Kumarapalli',
       'Lingarajapuram', 'Vasantha Vallabha Nagar', 'Kalhalli',
       'Kumaraswami Layout', 'Hadosiddapura', 'Kachanayakanahalli',
       'Yelenahalli', '6th block Koramangala', 'Vignana Nagar',
       'Canara Bank Colony', 'Hanumagiri', 'Benson Town',
       'Akshayanagara West', 'OLd Gurappanapalya', 'Ramanjaneyanagar',
       'B Channasandra', 'New Thippasandra', 'Gattigere', 'Kamakshipalya',
       'Dollars Colony', 'Pragathi Nagar', 'HAL 2nd Stage',
       'Sathya Sai Layout', 'Poorna Pragna Layout', 'Kenchenahalli',
       'Kundalahalli Colony', 'Amblipura', 'Vimanapura',
       'Dodsworth Layout', 'Devasthanagalu', 'Venugopal Reddy Layout',
       'Lake City', 'S R Layout', 'Sadduguntepalya', 'Mallathahalli',
       'Doddakammanahalli', 'Chikkathoguru', 'Richards Town',
       'BCC Layout', 'Vinayak Nagar', 'Jaladarsini Layout',
       'Brooke Bond First Cross', 'Glass Factory Layout',
       'Raghavendra Nagar', 'Bhuvaneswari Nagar', ' Electronic City',
       'Mathikere', 'Kempegowda Nagar', 'Nyanappana Halli', 'Nelamangala',
       ' Whitefield', 'Vaishnavi Layout', 'Naganathapura', 'Venkatapura',
       '3rd Phase JP Nagar', 'Devarachikkanahalli', 'Anjanapura',
       'Reliaable Tranquil Layout', 'Mailasandra', 'Chelekare',
       'Doopanahalli', 'Kattigenahalli', 'Varthur Road', 'Bethel Nagar',
       'Dollar Scheme Colony', 'Omarbagh Layout',
       'Aishwarya Crystal Layout', '2nd Block Jayanagar',
       'Nayandanahalli', 'DUO Layout', 'ISRO Layout', 'Hennur Bande',
       'Shampura', 'Richmond Town', 'Vishwanatha Nagenahalli',
       'Friends Colony', 'Shettigere', 'NTI Layout', 'Gunjur Palya',
       'Maithri Layout', 'Nobo Nagar', 'Krishna Reddy Layout',
       'Kuvempu Layout', 'Kaveri Nagar', 'Devi Nagar', 'Chikkabanavar',
       'Bommasandra Industrial Area', 'Stage-4 Bommanahalli',
       'Banashankari Stage V', 'Manorayana Palya', 'Sathya Layout',
       'Shanti Nagar', 'Jayamahal', 'Veer Sandra', 'Chennappa Layout',
       'Jeevan bima nagar', 'Lavakusha Nagar', 'Vittal Mallya Road',
       'Dena Bank Colony', 'Doddabidrakallu', 'NGR Layout',
       'Jnana Ganga Nagar', 'Ittamadu', 'Chokkanahalli', 'Vikram Nagar',
       'Sarvabhouma Nagar', 'Coconut Grove Layout', 'Kadabagere',
       'Anand Nagar', 'Kammanahalli', 'Janatha Colony',
       '1st Block Jayanagar', 'Veersandra', 'Kumbena Agrahara',
       'Hiremath Layout', 'Nagadevanahalli', 'Ramamurthy Nagar Extension',
       'Himagiri Meadows', 'Narayanappa Garden', 'Kempapura',
       'Carmelaram', 'Ankappa Layout', 'Jakkuru Layout', 'Maruthi Nagar',
       'Punappa Layout', 'Pampa Extension', 'Banaswadi',
       'Sanne Amanikere', 'Palanahalli', '2nd Stage Arekere Mico Layout',
       'BCMC Layout', 'Uday Nagar', 'Chaitanya Ananya',
       'Kacharakanahalli', 'Tigalarpalya', ' Banaswadi', 'Sugama Layout',
       'Hongasandra', 'Anugrah Layout', 'Bandepalya', 'AMS Layout',
       'RPC layout', 'Gulimangala', 'Addischetan Layout', 'Sadaramangala',
       'Konena Agrahara', 'Raghavendra Layout', 'Varsova Layout',
       'Raja Rajeshwari Nagar 5th Stage', '7th Block Jayanagar',
       'Bande Nallasandra', 'Upkar Layout', 'Singapura Village',
       'Canara Bank Layout', 'Queens Road', 'Hosapalya', 'Jagadish Nagar',
       'Siddapura', 'Rajasree Layout', 'Chikkadunnasandra',
       'Thirumalashettyhally', 'Vibuthipura', 'Kodigehalli', 'P&T Layout',
       'Varanasi', 'Virudhu Nagar', 'Ramanashree Enclave',
       'Chikku Lakshmaiah Layout', 'Shivaji Nagar', 'Chikkagubbi',
       'Kammagondahalli', 'Yeshwanthpur Industrial Suburb', 'Thirupalya',
       'Tirumanahalli', 'ITPL', 'NRI Layout', 'Adugodi', 'Sidedahalli',
       'Shanthi Pura', 'Anwar Layout', 'Doddanakundi Industrial Area 2',
       'RBI Layout', 'Shauhardha Layout', 'Bhoopsandra',
       '3rd Block Koramangala', 'Kuvempu Nagar',
       'Sri Balaji Krupa Layout', 'Govindapura', 'Ayappa Nagar',
       'Hessarghatta', 'Anantapuram', 'Chikka Banaswadi',
       'Akshayanagara East', 'Guddadahalli', 'Kashi Nagar',
       'Nanjappa Garden', 'Allalasandra', 'Maheswari Nagar', 'Udayagiri',
       'Mahalakshmi Layout', 'Rahmath Nagar', 'Halanayakanahalli',
       'Air View Colony', 'Amam Enclave Layout', 'Anantapura',
       'Mallappa Layout', 'Devarabeesana Halli', 'Chikbasavanapura',
       'Billamaranahalli', 'Jogupalya', 'Yemlur', 'Gulakamale',
       'Mahalakshmi Puram', 'Jakkasandra', 'Cooke Town', 'Virupakshapura',
       'Kenchenhalli', 'Sarvobhogam Nagar', 'Near International Airport',
       'Palace Road', 'Abshot Layout'])

sqft = st.number_input("Square Foot Area", step=5)

bath = st.slider("Bath", 0, 5)

size = st.selectbox("Size of the House", options=['2 BHK', '4 Bedroom', '3 BHK', '3 Bedroom', '1 RK', '4 BHK',
       '1 BHK', '5 BHK', '11 BHK', '5 Bedroom', '9 BHK', '2 Bedroom',
       '6 BHK', '7 BHK', '6 Bedroom'])

area_type = Predictions.encodeArea(areaType=area_type)
location = Predictions.encodeLocation(loc=location)
# sqft = Predictions.cleanSqft(sqft=sqft)
size = Predictions.encodeSize(size=size)



z = [[int(area_type), int(location), int(size), int(sqft), bath, balcony]]

st.write("The Predicted price is: ")
ans = model.predict(z)

ans = np.reshape(ans, (1, -1))

st.write(ans)